import fs from 'node:fs/promises';
import path from 'node:path';
import { createRequire } from 'node:module';
const { chromium } = createRequire(import.meta.url)(process.env.BASIN_PLAYWRIGHT_MODULE || 'playwright');
const out = path.resolve('output/browser-rehearsal');
await fs.mkdir(out, { recursive: true });
const browser = await chromium.launch({headless:true, ...(process.env.BASIN_BROWSER_EXECUTABLE ? {executablePath:process.env.BASIN_BROWSER_EXECUTABLE} : {})});
const context = await browser.newContext({viewport:{width:1600,height:1000},recordVideo:{dir:out,size:{width:1600,height:1000}},acceptDownloads:true});
const external = [];
await context.route('**/*', async route => {
  const url = new URL(route.request().url());
  if (['127.0.0.1','localhost'].includes(url.hostname) || ['data:','blob:'].includes(url.protocol)) return route.continue();
  external.push(url.href); await route.abort();
});
const page = await context.newPage();
const errors=[];
page.on('pageerror', e=>errors.push(e.message));
await page.goto(process.env.BASIN_URL || 'http://127.0.0.1:8521');
await page.getByRole('button',{name:'Generate',exact:true}).waitFor({timeout:60000});
await page.screenshot({path:path.join(out,'01-stations.png')});
await page.getByRole('button',{name:'Generate',exact:true}).click();
await page.getByText('Approved',{exact:true}).waitFor({timeout:60000});
await page.screenshot({path:path.join(out,'02-workspace.png')});
await page.getByText('Compare scenarios and priorities',{exact:true}).click();
await page.getByText('Compare two or three candidates',{exact:true}).scrollIntoViewIfNeeded();
await page.screenshot({path:path.join(out,'03-comparison.png')});
await page.getByText('Review',{exact:true}).first().click();
await page.getByRole('tab',{name:'Reference & provenance'}).click();
await page.getByText('Evidence and assumptions',{exact:true}).scrollIntoViewIfNeeded();
await page.screenshot({path:path.join(out,'04-evidence.png')});
await page.getByRole('textbox',{name:'Public disagreement',exact:true}).fill('Internal rehearsal: airport observations and catchment rainfall have different spatial meanings.');
await page.getByRole('textbox',{name:'Public comparability limits (dates, definitions, units, geography)',exact:true}).fill('Geographic applicability is unvalidated. Request practitioner review.');
await page.getByRole('button',{name:'Record unresolved disagreement',exact:true}).click();
await page.getByText('Disagreement saved; both evidence records retained.',{exact:true}).waitFor();
await page.getByText('Reservoir simulation',{exact:true}).first().click();
await page.getByText('All experiment assumptions and accounting',{exact:true}).scrollIntoViewIfNeeded();
await page.screenshot({path:path.join(out,'05-experiment.png')});
await page.getByText('Cumulative rainfall',{exact:true}).first().click();
// The public demo recording is an internal rehearsal, not practitioner approval.
const scenarioBox=page.getByRole('combobox',{name:'Scenario',exact:true});
await scenarioBox.click();
const options=await page.getByRole('option').allTextContents();
const shortlist=options.filter(t=>t.includes('shortlisted')).map(t=>t.match(/B-\d+/)[0]);
await page.keyboard.press('Escape');
if(shortlist.length!==6) throw new Error('Could not identify the six shortlisted scenarios');
for(const id of shortlist){
  await scenarioBox.click();
  await page.getByRole('option',{name:new RegExp('^'+id+' ')}).click();
  await page.getByRole('textbox',{name:'Review note',exact:true}).fill('Automated browser rehearsal approval; not practitioner validation.');
  await page.getByRole('button',{name:'Accept',exact:true}).click();
  await page.getByRole('button',{name:'Accept',exact:true}).waitFor();
}
await page.getByText('Exports',{exact:true}).first().click();
await page.getByRole('button',{name:'Build verified export',exact:true}).click();
await page.getByRole('button',{name:'Download ZIP',exact:true}).waitFor({timeout:60000});
await page.screenshot({path:path.join(out,'06-export.png')});
const downloadEvent=page.waitForEvent('download');
await page.getByRole('button',{name:'Download ZIP',exact:true}).click();
const downloaded=await downloadEvent;
await downloaded.saveAs(path.join(out,'BASIN-browser-rehearsal.zip'));
await page.getByText('Data',{exact:true}).first().click();
await page.getByText('Snapshot metadata & quality policy',{exact:true}).waitFor();
await page.screenshot({path:path.join(out,'07-data.png')});
if (errors.length) throw new Error(JSON.stringify(errors));
await fs.writeFile(path.join(out,'report.json'),JSON.stringify({external_requests_blocked:external,browser_errors:errors,scope:'Browser requests to nonlocal hosts blocked; source, generation, comparison, evidence conflict, illustrative experiment, all six approvals, verified export and downloaded ZIP inspected. Actual presentation laptop remains untested.'},null,2));
const video=page.video();
await context.close();
if(video) await video.saveAs(path.join(out,'BASIN-internal-rehearsal.webm'));
await browser.close();
console.log(JSON.stringify({external_requests_blocked:external,errors,output:out}));
