[server]
address = "127.0.0.1"
headless = true
maxUploadSize = 5
[browser]
gatherUsageStats = false
[theme]
base = "light"
font = "sans serif"
baseRadius = "0.65rem"
buttonRadius = "0.55rem"
showWidgetBorder = true

[theme.light]
primaryColor = "#2D6683"
backgroundColor = "#F6F8F9"
secondaryBackgroundColor = "#E9EEF1"
textColor = "#202A30"
borderColor = "#B8C2C8"

[theme.light.sidebar]
backgroundColor = "#EFF3F5"
secondaryBackgroundColor = "#E2E8EB"

[theme.dark]
primaryColor = "#2D6683"
backgroundColor = "#151A1E"
secondaryBackgroundColor = "#232B31"
textColor = "#E7ECEF"
borderColor = "#4A565E"

[theme.dark.sidebar]
backgroundColor = "#11161A"
secondaryBackgroundColor = "#20272C"
